### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by abmayuri** [EtherealAO/UmamusumeResponseAnalyzer#14]
![CQ)TFB}(EE{JS(KIR1Z~~$3](https://user-images.githubusercontent.com/105031168/167060471-03119d3b-8298-40fc-8dca-a2eb07a1337d.png)
更新完毕之后回退点击启动就弹出这个框 然后自动关闭了

**Comment by EtherealAO** [comment]
请更新到 https://github.com/EtherealAO/UmamusumeResponseAnalyzer/releases/tag/v1.7.2-hotfix
