### ISSUE TITLE
从旧版本更新时可能遇到的问题

### ISSUE THREAD

**Issue by benx1n** [EtherealAO/UmamusumeResponseAnalyzer#16]
新版本中本地添加了climaxitems.json这个文件
如果从旧版本中选择数据更新，重启程序后选择启动将会只输出事件，需要重新更新一次数据以创建该文件才能正常输出训练信息和道具
是否能增加一个提示或启动时检查本地数据完整性的功能？

**Comment by Array-Cats** [comment]
我倒是不管是从旧版更新还是直接新版都无法输出训练/道具信息

**Comment by benx1n** [comment]
我测试了一下，新版未解锁商店时无法输出训练信息

**Comment by Array-Cats** [comment]
我之前测试是商店刚开，然后这边没什么显示，的确开启商店后进入到下一回合就会显示了。

不过隔壁胡萝卜汁是在开启商店的那一回合就会显示商店道具了，感觉这边还有待完善。

**Comment by Array-Cats** [comment]
的确是，感觉作者可能把信息显示的方式做的太简单粗暴了

**Comment by EtherealAO** [comment]
>是否能增加一个提示或启动时检查本地数据完整性的功能？

在更新那边重复执行一次Update应该也可以
>新版未解锁商店时无法输出训练信息
以及已开启商店但重启程序后，如果不进行购买也是不会显示训练和道具信息的

有几个NullReference，现在应该好了

>不过隔壁胡萝卜汁是在开启商店的那一回合就会显示商店道具了，感觉这边还有待完善。

我没太注意，等下次进巅峰杯再看

**Comment by Array-Cats** [comment]
再给一点改进的建议吧：
1.显示道具回合数还剩下1/0回合时用红色标注字体。（当然个人的看法其实更希望能够将道具的最后一回合显示为1而不是0，毕竟游戏里面也是这样）

2.对于促销的道具价格可以使用其他颜色显示

3.以及能否将道具列表和训练列表分开，目前摆放的形式看起来并不是很顺眼

综合一下可以考虑使用下图的这种表现形式：
![](https://s3.bmp.ovh/imgs/2022/05/07/39f51a3bc8d90c08.png)


当然最终决定权在作者，这里只是个人的使用后的一些看法和建议。

**Comment by EtherealAO** [comment]
> 1.
d57f7ef2a1dc218c3a1c0d5ca139d940475da993 剩余回合应该在这个commit里都改成按游戏内方式显示了啊

> 2.
颜色会改，考虑到colomn width 价格应该是不会显示了，会按折扣给名字上色，根据剩余T数给个数/xT上色。等发布1.8.0才是全都弄完了的时候，现在没太多时间去养巅峰杯

> 3. 
最开始的时候就是这种格式，但是在我的terminal里这样太丑了，连续显示几次的时候非常分散，简直是灾难，所以才放到footer里

**Comment by benx1n** [comment]
> 有几个NullReference，现在应该好了

测试下来没问题了

> 最开始的时候就是这种格式，但是在我的terminal里这样太丑了，连续显示几次的时候非常分散，简直是灾难，所以才放到footer里

关于道具显示还有一点小小的建议：目前体力上限+4MAX占用了两行，能否缩减该词条以更美观一些？
![image](https://user-images.githubusercontent.com/48101337/167250875-304fd62c-584a-412a-b61a-d378fd224959.png)

以及之前我在您的数据生成项目那开了个Pr用以添加有关训练Buff事件的成功分支，您有空的时候能否帮忙review一下呢？

**Comment by EtherealAO** [comment]
> > 有几个NullReference，现在应该好了
> 
> 测试下来没问题了
> 
> > 最开始的时候就是这种格式，但是在我的terminal里这样太丑了，连续显示几次的时候非常分散，简直是灾难，所以才放到footer里
> 
> 关于道具显示还有一点小小的建议：目前体力上限+4MAX占用了两行，能否缩减该词条以更美观一些？ ![image](https://user-images.githubusercontent.com/48101337/167250875-304fd62c-584a-412a-b61a-d378fd224959.png)
> 
> 以及之前我在您的数据生成项目那开了个Pr用以添加有关训练Buff事件的成功分支，您有空的时候能否帮忙review一下呢？

生成的时候没匹配完整，现在应该好了
