### ISSUE TITLE
無法啟用

### ISSUE THREAD

**Issue by Halz1oN** [EtherealAO/UmamusumeResponseAnalyzer#18]
想問下第一次把exe下下來後是可以直接開不用放在遊戲主目錄嗎
點開exe之後選更新數據文件到這會閃退
![Screenshot 2022-05-10 230912](https://user-images.githubusercontent.com/105267180/167661587-68c9f7e5-331c-4c15-83d8-feac82a8e44b.jpg)
然後點啟動好像也不能讀取到東西
![Screenshot 2022-05-10 231011](https://user-images.githubusercontent.com/105267180/167661804-87a2cd36-2f06-4e9c-bcc1-757c53be8b54.jpg)

**Comment by EtherealAO** [comment]
1 直接开 放在哪都无所谓 不用放在目录里
2 请在release中下载最新版本 v1.8.1
