### ISSUE TITLE
还是无法正常启动

### ISSUE THREAD

**Issue by Halz1oN** [EtherealAO/UmamusumeResponseAnalyzer#19]
不好意思今天再试了重新下载还是同样更新闪退无法正常启动，想问下我有在用EXNOA-CarrotJuicer这个插件而且没删除，会有冲突吗？是不是需要把EXNOA-CarrotJuicer的文件删除才能用

**Comment by EtherealAO** [comment]
请和之前的issue一样附上报错的截图

**Comment by Halz1oN** [comment]
![unknown (1)](https://user-images.githubusercontent.com/105267180/167828875-014dd6b1-26f8-4575-9a72-77eacce692a7.png)
![unknown (2)](https://user-images.githubusercontent.com/105267180/167828883-b9da7923-2f4e-492c-bafb-ad22786af1b8.png)

**Comment by Halz1oN** [comment]
到了这就一下子闪退了  来不及拉到右边看完整句子抱歉

**Comment by Halz1oN** [comment]
啊我已經是下載在1.8.1版下面下的exe檔了  我下1.8.0的好像也是顯示1.7.6

**Comment by Halz1oN** [comment]
从这两个链接下下来的也是1.7.6  晕了  跟windows defender那些有关系吗  第一次开的时候有弹窗不让执行

**Comment by EtherealAO** [comment]
https://github.com/EtherealAO/UmamusumeResponseAnalyzer/releases/tag/v1.8.4
这个版本应该可以了
版本是1.7.6是因为我忘记改程序的版本号了（

**Comment by benx1n** [comment]
似乎在1.8.6中还会遇到问题，分别是更新和启动时输出的错误
![image](https://user-images.githubusercontent.com/48101337/168426276-44ead098-efa9-4d11-9ff3-7dcf38fed63a.png)
![image](https://user-images.githubusercontent.com/48101337/168426277-c64a0f6d-7b10-4542-bc46-55a61f0648c0.png)
