### ISSUE TITLE
求助，启动后毫无作用

### ISSUE THREAD

**Issue by fsh445387322** [EtherealAO/UmamusumeResponseAnalyzer#2]
启动后除了一个检测到正在运行的umamuse.exe 已启动的提示以外，什么都没有

抓包软件用的CarrotJuicer，软件可以正常使用读取。打开Analyzer，更新，提示成功，点击启动，
启动后除了一个检测到正在运行的umamuse.exe 已启动的提示以外，什么都没有。
我是哪里有问题吗？

**Comment by EtherealAO** [comment]
[若非使用修改版的umamusume-localify，则需要在对应的插件配置中将URL设置为http://127.0.0.1:4693](https://github.com/EtherealAO/UmamusumeResponseAnalyzer/wiki/%E5%AE%89%E8%A3%85-Installation)
[CarrotJuicer说明](https://github.com/CNA-Bld/EXNOA-CarrotJuicer/blob/master/README.md#notifier)
