### ISSUE TITLE
有时软件无法正常工作

### ISSUE THREAD

**Issue by Array-Cats** [EtherealAO/UmamusumeResponseAnalyzer#20]
目前并不清楚是umamusume-localify的问题还是这里的问题，姑且先在这里发issues了。

具体现象是有时候软件无法获取数据（只显示已启动），但是重开软件/游戏以后（可能需要折腾几次）会恢复正常。

跟软件/游戏启动的顺序无关，不管是先启动游戏还是先启动软件都有概率触发，而且主要集中在每次开电脑后第一次启动（记忆中恢复了以后再关机之前后面再启动就没有遇到过这个问题）

**Comment by EtherealAO** [comment]
[[#] 修复裁剪未使用的文件导致无法正常输出内容的BUG](https://github.com/EtherealAO/UmamusumeResponseAnalyzer/commit/50bd02881ad30303bf6c69cba9fcc1f58819775f)
可能和这个有关，不知道为什么在那里加代码会导致dynamic相关的东西被编译器trim掉，现在应该没问题了？

**Comment by Array-Cats** [comment]
> [[#] 修复裁剪未使用的文件导致无法正常输出内容的BUG](https://github.com/EtherealAO/UmamusumeResponseAnalyzer/commit/50bd02881ad30303bf6c69cba9fcc1f58819775f) 可能和这个有关，不知道为什么在那里加代码会导致dynamic相关的东西被编译器trim掉，现在应该没问题了？

Emm，似乎还是有，不过这次是发生在养成结束后进入JJC，软件这边并没有显示JJC信息而是停留在了养成结算。

**Comment by EtherealAO** [comment]
未成功复现

**Comment by Array-Cats** [comment]
目前我也没遇到第二次，所以只能说继续观察

**Comment by Array-Cats** [comment]
目前发现1.8.10版本还是有类似的问题

目前遇到问题的步骤是：1.启动软件；2.启动游戏；3.第一次进入JJC。
现象是软件不显示数据，仍然停留在“已启动”

不过第二回进入JJC就能正常显示了，且中间没有其他的操作。

@EtherealAO
