### ISSUE TITLE
 启动后报错

### ISSUE THREAD

**Issue by yeshunn** [EtherealAO/UmamusumeResponseAnalyzer#26]
![未命名](https://user-images.githubusercontent.com/105560807/168442812-16c74326-47a1-4615-a999-159ea96687ec.jpg)
如图所示  更新至最新版本也没用

**Comment by Hoshiyomi0** [comment]
同樣狀況
發現到更新后這裏的文件都是404 not found
![image](https://user-images.githubusercontent.com/98295236/168453256-055e4e58-1de0-472d-89c1-c7e6f74588d3.png)

**Comment by EtherealAO** [comment]
[v1.8.7](https://github.com/EtherealAO/UmamusumeResponseAnalyzer/releases/tag/v1.8.7)
