### ISSUE TITLE
更新后启动程式随即崩溃

### ISSUE THREAD

**Issue by VivaX1k** [EtherealAO/UmamusumeResponseAnalyzer#27]
命令行介面弹出来了然后马上就crash了, 没有东西显示
然后尝试回滚到1.84/1.76/清空%localappdata%/UmamusumeResponseAnalyzer/关防毒都失效了

清空local崩溃后只会留下一份.config
[config.txt](https://github.com/EtherealAO/UmamusumeResponseAnalyzer/files/8694265/config.txt)

**Comment by Hoshiyomi0** [comment]
一樣的問題 研究了半天也不懂要怎麽解決

**Comment by EtherealAO** [comment]
删掉%temp%目录下的latest-UmamusumeResponseAnalyzer.exe

**Comment by Hoshiyomi0** [comment]
> 删掉%temp%目录下的latest-UmamusumeResponseAnalyzer.exe

可是我的temp裏面沒有這個文件

**Comment by EtherealAO** [comment]
尝试更新[v1.8.8](https://github.com/EtherealAO/UmamusumeResponseAnalyzer/releases/tag/v1.8.8)

**Comment by VivaX1k** [comment]
更新1.8.9出现了以下情况（
![sk133](https://user-images.githubusercontent.com/99403993/168471246-d720cc83-7f05-4a8e-b852-e89535466687.png)
显示是1.8.8，但d'q's的确是在release下的1.8.9（

**Comment by qq404181432** [comment]
和上面一样的情况 坐标国内

**Comment by EtherealAO** [comment]
[v1.8.10](https://github.com/EtherealAO/UmamusumeResponseAnalyzer/releases/tag/v1.8.10)

**Comment by a903395416** [comment]
![image](https://user-images.githubusercontent.com/26520615/168475507-fa1e42da-b634-40fe-9b6e-48ec932faae7.png)
更新1.8.10后打开程序闪退了
