### ISSUE TITLE
更新后报了错

### ISSUE THREAD

**Issue by yuszelim** [EtherealAO/UmamusumeResponseAnalyzer#28]
今天更新后点运行出现如下错误
![3](https://user-images.githubusercontent.com/105581472/168462505-75b22b96-10fc-4b5b-8cd6-13469b477df8.png)

然后打开local里面的json 档案发现全部都显示了404
![1](https://user-images.githubusercontent.com/105581472/168462523-0f35a591-1bb8-478e-8445-7c3c619e0d6d.png)
![2](https://user-images.githubusercontent.com/105581472/168462528-fc878586-ad20-472b-9311-e07734c5443b.png)

**Comment by yuszelim** [comment]
暂时把这几个json档案删除可以继续正常运行

**Comment by Hoshiyomi0** [comment]
我也試過刪掉但是不會顯示任何東西

**Comment by yuszelim** [comment]
可以先用1.8.6的把正常的json档案抓下来。。。别敲回车
![擷取](https://user-images.githubusercontent.com/105581472/168465548-8a2fdee2-f757-4360-bed8-48d091e942f9.PNG)

然后把正常的json复制一份去其他地方，等程序自动更新1.8.7后覆盖回去

**Comment by Hoshiyomi0** [comment]
原來 我是有抓到1.8.7的json檔案但是沒抓到那個config 我試試看

**Comment by EtherealAO** [comment]
[v1.8.8](https://github.com/EtherealAO/UmamusumeResponseAnalyzer/releases/tag/v1.8.8)
