### ISSUE TITLE
求助，和楼上一个问题

### ISSUE THREAD

**Issue by qwe336424** [EtherealAO/UmamusumeResponseAnalyzer#3]
开了vpn才能更新程序，更新完显示已启动但是没有选项加载出来

**Comment by EtherealAO** [comment]
#2 
[若非使用修改版的umamusume-localify，则需要在对应的插件配置中将URL设置为http://127.0.0.1:4693](https://github.com/EtherealAO/UmamusumeResponseAnalyzer/wiki/%E5%AE%89%E8%A3%85-Installation)
[CarrotJuicer说明](https://github.com/CNA-Bld/EXNOA-CarrotJuicer/blob/master/README.md#notifier)

**Comment by qwe336424** [comment]
感谢，现在能用了
