### ISSUE TITLE
最新版本Realease無法正常選擇更新

### ISSUE THREAD

**Issue by KohakuBlueleaf** [EtherealAO/UmamusumeResponseAnalyzer#37]
下載了最新版的Release，啟動後選擇更新會出現以下錯誤。
![image](https://user-images.githubusercontent.com/59680068/169680227-7e08d066-254f-4f21-9670-3e14519f8341.png)

**Comment by EtherealAO** [comment]
https://github.com/EtherealAO/UmamusumeResponseAnalyzer/releases/tag/v1.8.11.1
