### ISSUE TITLE
部分Event选项字体颜色“丢失”

### ISSUE THREAD

**Issue by Array-Cats** [EtherealAO/UmamusumeResponseAnalyzer#38]
如图的圈起的选项之前的版本（1.8.10及以前）是红色字体，现在变成跟普通选项一样的白色字体。
我不知道其他个别的是否也有这个现象，至少这个我的印象是清晰的

![dRIL1.png](https://s1.328888.xyz/2022/05/22/dRIL1.png)

**Comment by EtherealAO** [comment]
更新下数据试试？

**Comment by EtherealAO** [comment]
https://github.com/EtherealAO/UmamusumeResponseAnalyzer/releases/tag/v1.8.11.3
