### ISSUE TITLE
部分事件没有显示

### ISSUE THREAD

**Issue by Touristx** [EtherealAO/UmamusumeResponseAnalyzer#39]
目前已知的是代理理事长的出门和福来事件都没显示

**Comment by Touristx** [comment]
打针事件文字显示也有问题
![QQ截图20220522164529](https://user-images.githubusercontent.com/82885049/169686567-e7cfa364-d220-4be0-8861-d63ece32332c.png)

**Comment by EtherealAO** [comment]
更新下数据试试

**Comment by Touristx** [comment]
版本1.8.11.2，似乎以及没有数据可更新了，昨晚试了几把，只有代理出门、福来+4不显示，然后打针显示有问题

**Comment by Halz1oN** [comment]
新智卡cb的事件也沒讀取到

**Comment by yuszelim** [comment]
同样遇到代理问题，不过我还原了1.8.8将就用了

**Comment by EtherealAO** [comment]
https://github.com/EtherealAO/UmamusumeResponseAnalyzer/releases/tag/v1.8.11.3
