### ISSUE TITLE
已配置Notifier后仍无法输出相关信息

### ISSUE THREAD

**Issue by benx1n** [EtherealAO/UmamusumeResponseAnalyzer#4]
插件使用的是EXNOA-CarrotJuicer
已在配置文件中开启Notifier并指向本地4396端口
不启动UmamusumeResponseAnalyzer运行游戏时CarrotJuicer会打印Notifier超时错误
启动UmamusumeResponseAnalyzer后不再提示但插件无任何输出
![image](https://user-images.githubusercontent.com/48101337/163175991-97d6774b-5897-4f8e-9550-12084694581a.png)

**Comment by EtherealAO** [comment]
> Failed to notify listener: 2

请检查你的CarrotJuicer配置是否正确
> 若非使用修改版的[umamusume-localify](https://github.com/EtherealAO/umamusume-localify)，则需要在对应的插件配置中将URL设置为http://127.0.0.1:4693

notifier_host必须为`http://127.0.0.1:4693`，不能是`http://127.0.0.1:4693/`。

**Comment by benx1n** [comment]
抱歉前两天没看到issue的更新，这是我的config配置
![image](https://user-images.githubusercontent.com/48101337/164214373-67352fbb-401e-4d54-aeb7-0249c5db200c.png)

**Comment by benx1n** [comment]
抱歉前两天没收到issue的推送，这是我的config配置
![image](https://user-images.githubusercontent.com/48101337/164214906-8d77c3d9-d9d5-4b0b-bcbe-518f3d1cb780.png)

**Comment by EtherealAO** [comment]
EXNOA-CarrotJuicer v1.7.0在我这里工作正常，可以使用netstat等命令检查UmamusumeResponseAnalyzer是否成功监听上4693断口

**Comment by benx1n** [comment]
看了一下 未启动时无占用
启动后被pid＝4的进程监听了
![image](https://user-images.githubusercontent.com/48101337/164386073-cff9ba09-ab90-489c-84db-997f58745ec1.png)

**Comment by benx1n** [comment]
返回的是200，但是使用了修改版的umamusume-localify还是同样的问题，就很怪

**Comment by benx1n** [comment]
重新排查了下，是我这边的问题
选项界面手动取消了功能开启，这个[X]还是挺容易误导的）
