### ISSUE TITLE
不知道大家的Analyzer会不会出现保存的数据包为.br的问题

### ISSUE THREAD

**Issue by wulala131** [EtherealAO/UmamusumeResponseAnalyzer#40]
AppData\Local\UmamusumeResponseAnalyzer\packets中的.br文件无法被Hakuraku所读取，记得之前版本还是.msgpack，或者有哪个网站可以分析.br文件吗

**Comment by EtherealAO** [comment]
.br是用brotli压缩的格式，用任意支持的压缩软件解压之后就是原来的.msgpack，下一个release就会改回保存.msgpack，但是仍然只保留一天
