### ISSUE TITLE
程序出现“解析Response时出现错误”

### ISSUE THREAD

**Issue by Array-Cats** [EtherealAO/UmamusumeResponseAnalyzer#41]
报错的内容可以见末尾的截图，目前在进入JJC/JJC内刷新对手/准备开始养成/养成过程中都有遇到该报错，暂时没有发现影响使用的地方（虽然会偶尔报错，但是该显示数据基本还是会显示）

![l8mvS.png](https://s1.328888.xyz/2022/05/24/l8mvS.png)
JJC刷新

![l83LR.png](https://s1.328888.xyz/2022/05/24/l83LR.png)
进入JJC

![l8O1v.png](https://s1.328888.xyz/2022/05/24/l8O1v.png)
准备开始养成

![l8KCi.png](https://s1.328888.xyz/2022/05/24/l8KCi.png)
养成过程中

**Comment by EtherealAO** [comment]
程序无法分辨哪个请求是哪个，只能尝试全部反序列化然后挨个试，对于某些不是那么标准的Response（参考https://github.com/CNA-Bld/EXNOA-CarrotJuicer/issues/5 ）就会报错。
加这个是为了在反馈BUG的时候能有一个stacktrace，不至于人工复现，如果所有功能运行都正常就可以不用管
