### ISSUE TITLE
图片内的问题如何解决

### ISSUE THREAD

**Issue by xxw1b** [EtherealAO/UmamusumeResponseAnalyzer#8]
![T ESKM%{ %`T0X5Y(E4%V6W](https://user-images.githubusercontent.com/104729483/166156035-cae64dda-dfc5-4766-900f-528a83efd2e7.png)

**Comment by EtherealAO** [comment]
#7 
github是github，被污染的是raw.githubusercontent.com不是github.com
程序默认会使用系统代理，请确认你的程序是通过代理进行连接的
